#define FLOW_TAP_TERM 20
#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 180

#define PERMISSIVE_HOLD

#define COMBO_TERM 40

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "5JOgw/yoGnLx"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 10

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

